### ISSUE TITLE
Standardization of files in each WG repo

### ISSUE THREAD

**Issue by yash2002109** [chaoss/community#277]
Hi everyone,

Now that we're almost through with restructuring the working group repositories. We're also looking to create a standardized version for the set of files that are present in each WG repo. This will help increase uniformity in the way information is presented  in these repos.

The following set of files have been proposed for standardization:

-  README.md
    - The main README.md files in each WG repo are currently following different structures.
    - Proposed structure - https://docs.google.com/document/d/1pfipIiaemdtdiDQpvY7jOKhKzsv_3lXLLsbJiByl5GU/edit?usp=sharing
    -  Issues can be found in each WG repo discussing this in detail (e.g.- [wg-common/issues/116](https://github.com/chaoss/wg-common/issues/116))
    
- focus-areas/README.md & focus-areas/\<focus-area-name\>/README.md
    - These README files also follow different structures.
    - Similar to the main README.md we're looking to create a common structure for these files also.
    - #276 discusses this in greater detail.
    
- CONTRIBUTING.md
    - The common content of this file will be moved to the community handbook to create a master contributing guide.
    - This file would be redesigned so it points to the guide in the handbook.
    - This is being done to follow the SSOT practice and ease maintenance.

- code-of-conduct.md
    - This file would also be redesigned so it points to [governance/code-of-conduct.md](https://github.com/chaoss/governance/blob/master/code-of-conduct.md)
    - Reasons are the same as for CONTRIBUTING.md.

**Comment by GeorgLink** [comment]
The files are great. Thanks @yash2002109

**Comment by GeorgLink** [comment]
I know you did a lot of work standardizing all WG repos. Is there anything left to be done or can we close this issue?

**Comment by ElizabethN** [comment]
I'm going to close this, as I think any remaining issues are being sorted out elsewhere. Thanks so much for your work on this @yash2002109 😻
