### ISSUE TITLE
Metrics without contributor lists

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/community#290]
I noticed that older metrics have contributor lists, while some newer metrics do. That is OK until we need to add a contributor to an older metric.

Check out this PR: https://github.com/chaoss/wg-dei/pull/373

I could not add a contributor to the project-and-community/code-of-conduct metric because there is no list for it.

How should we handle this? I'm sure there are many different methods but I want to open it up.

**Comment by GeorgLink** [comment]
Could we add the heading when needed?

**Comment by Nebrethar** [comment]
@GeorgLink

I’m not sure. If we add only new contributors to an older metric, we would then have an incomplete contributor list on that metric.

I have an idea, but it needs working through. We could have a disclaimer of some sort that says “Contributors since Release 2021-02” or something like that…?

**Comment by ElizabethN** [comment]
>I have an idea, but it needs working through. We could have a disclaimer of some sort that says “Contributors since Release 2021-02” or something like that…?

I like this approach. I think during one discussion about this topic, it was brought up that to go back and retroactively contact everyone who worked on these foundational metrics, and get their consent to be recognized, would be a very time consuming task. It would definitely be easier to indicate these are the contributors since 2021-02 and just move forward from there.

**Comment by GeorgLink** [comment]
I also like the idea.

What if someone worked on the metric before 2021-02 and would like to be recognized? Would we still add them?

**Comment by ElizabethN** [comment]
Would this be something for the operations team to implement? I feel like it will cut across all metrics in all working groups.

**Comment by germonprez** [comment]
I like the idea of Known Contributors. I don't want to add too many disclaimers to metrics. I think it's completely fine to have older metrics not have the contributor list as they were created before we recorded this.
