### ISSUE TITLE
Metrics Release 2022-03 Ideas

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#292]
During our latest weekly Community Call, we had an idea around our next Metrics Release in 2022. That idea is to do a **Metrics Audit**. We should make it a practice to periodically go back and review all "old" metrics for updates and improvements, and to make sure the language is clear and that the metrics are still relevant in the context of open source as it currently stands.

We're using this issue as kind of placeholder for this task, and any other ideas we have for improving our metrics release. Please feel free to drop any comments or ideas here. 🙌

**Comment by ElizabethN** [comment]
[As discussed in today's Community Call](https://docs.google.com/document/d/1PMDWc6xMe0fNE7shxTK5_HE_ykRBG5w55_Zx5hvzsEY/edit?pli=1#), while we're going back and doing the Metrics Audit, we should include a review of any data ethics issues that might touch on the data included in the metrics. We should add the appropriate note in the Implementation section as discussed.

**Comment by germonprez** [comment]
@ElizabethN is this done? Can this issue be closed?

**Comment by ElizabethN** [comment]
@germonprez yeah, I think so. we have been doing the audit and have incorporated the privacy statement to the metrics in the 2022-04 release. :+1:
