### ISSUE TITLE
Add Community Culture page to handbook?

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/community#293]
Moving @jaskiratsingh2000's suggestion from https://github.com/chaoss/community-handbook/pull/25#issuecomment-942103186

> Hi @ElizabethN @GeorgLink This issue caught my eye and I really liked the concept of informing to community and I highly appreciate the @ElizabethN for initiating this but I am not fully convinced that writing this much on the existing page would be enough
> 
> >    If you plan to be away from the CHAOSS project for a period of time, it's helpful to communicate that to other community members by changing your Slack Status or mentioning it in a Working Group meeting.
> 
> So I just have an idea that why don't we create a specific page with the name something like "Community Culture" and within this we elaborate upon the above mentioned sentence with all the details like adding screenshots, My understanding says that this page is not only for writing about informing the community instead the Community Culture would contain all the details relevant to what community has been doing bit internally/externally. I once remembered that @GeorgLink you mentioned about CHAOSS people mentoring for career guidance or higher studies to students or interns they have worked with and who are willing to seek such guidance. Correct me if I am wrong? So taking this thing into consideration I belive that it would be good to have a page for the community culture where we could define all such types of the activities in detail.
> 
> Let me know @ElizabethN @GeorgLink @germonprez What do you think about this above idea?

**Comment by germonprez** [comment]
Hi everyone. Do we have the login credentials for the Handbook? We either need to get these or remove and rebuild the handbook it.

**Comment by ElizabethN** [comment]
The information is here https://github.com/chaoss/community-handbook/, so at least we have the files for converting them into the knowledgebase. Since we also don't have the steps to adding or editing the handbook, we've been keeping a list of new docs to be added here: https://github.com/chaoss/community/issues/321. 

We can probably close this issue since it's being handled in other places.

**Comment by GeorgLink** [comment]
> Do we have the login credentials for the Handbook?

Yes, we do have the credentials. Who needs access?

**Comment by germonprez** [comment]
Elizabeth does. Right now, we aren't able to make changes in GH and get them reflected in the handbook.

**Comment by GeorgLink** [comment]
@jaskiratsingh2000 has always fixed this in the past. Not sure if he's around and would be able to fix this again for us.

My solution would be to disable the GitHub synchronization because it keeps failing us. This would mean we always edit the Handbook in GitBook.

**Comment by ElizabethN** [comment]
A few of us have reached out a few times via different channels and haven't gotten a response, so I'm guessing he's just super busy. Thanks for trying @GeorgLink! We will just add new docs to the new knowledgebase and go forward from there.

**Comment by ElizabethN** [comment]
I believe this information is included in the new handbook information so I'm closing this issue. Thanks everyone! :heart:
