### ISSUE TITLE
Providing Guidance to Working Groups Around Privacy

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#294]
During multiple discussions in our weekly Community Call and at CHAOSScon, the idea was surfaced that we should be providing guidance to our Working Groups around the consideration of privacy and ethics while developing metrics. For instance, sometimes our metrics include PII (Personally Identifiable Information) and we feel it's important to flag this for anyone who is using this metric in practice. 

This "guidance" will consist of 3 things:
- A central document describing the levels of PII, proper handling of data, and other considerations for those using metrics in practice
 - An addition to the Metrics Template that prompts the Working Group to have a thoughtful discussion around whether or not there could be data privacy issues in the collection of data in the metric, and a recommended statement under "Implementation". This statement will point to that central document and will be optional.
 - A line item in our Metrics Quality Checklist, for reviewers to double-check that data privacy was considered.

We will also include a data privacy review of previously released metrics when doing our [Metrics Audit for next release](https://github.com/chaoss/community/issues/292).

(For context, we have a similar framework for thinking about how a metric might impact DEI).

Thanks to @lucasgonze for championing this!

**Comment by GeorgLink** [comment]
Thanks for the draft @lucasgonze

**Comment by lucasgonze** [comment]
With regard to Silona's comments today on specific regulations in the EU, I have added a "# Relevant Regulations" section for gathering data on concrete restrictions.

**Comment by germonprez** [comment]
I'm closing this as the privacy/ethics statement has been added to all metrics -- even the Chinese/Mandarin release
