### ISSUE TITLE
The tutorial document link doesn't work 

### ISSUE THREAD

**Issue by timshen** [chaoss/community#297]
https://oss-augur.readthedocs.io/en/master/getting-started/toc.html mentioned below leads to a 404 page
[](url
<img width="1186" alt="Screen Shot 2021-10-26 at 2 10 10 PM" src="https://user-images.githubusercontent.com/2637142/138819080-3f91f5f3-02d7-4412-8f41-4ec0b452a5b4.png">
)

**Comment by ElizabethN** [comment]
I did a little digging and I think it's a break because we changed master->main. Here is the new link (https://oss-augur.readthedocs.io/en/main/getting-started/toc.html), and I'll submit a PR in the website repo. Thanks for bringing this up @timshen!

**Comment by ElizabethN** [comment]
Looks like this has already been fixed - it's all good!
