### ISSUE TITLE
CHAOSS Brand Kit

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#298]
As CHAOSS grows and the visibility of our work continues to increase, it's important to keep our brand intact and consistent and have a polished look. I'm opening this issue to allow for async discussion about this, as I know not everyone is at the community meetings all the time.

Feel free to drop your thoughts here!

cc @uoduckswtd1

**Comment by GeorgLink** [comment]
This is super important!

We have the Media https://chaoss.community/media/ with links to the logo - that's the closest we have to a brand kit.

We also have the slide template that we have been using. Example: https://docs.google.com/presentation/d/1n_Kpg6wWXUH-S2RZErHXT4tkort6gZdK1RcGVLgNbik/edit#

**Comment by ElizabethN** [comment]
During today's weekly Community Call, @uoduckswtd1 kindly offered to start a Brand Guidelines document for us. Thank you!! :pray:

**Comment by ElizabethN** [comment]
Update for the masses: this work continues and we are meeting to discuss next week.

**Comment by ElizabethN** [comment]
@Ruth-ikegah @xiaoya-yaya do you know if [these brand guidelines](https://docs.google.com/presentation/d/1BZSBa4Ttji95NTPwHcVjcu-CgiuwBezd/edit?usp=share_link&ouid=107031992323000623162&rtpof=true&sd=true) are linked anywhere in the handbook? I feel like we've talked about this so many times but I'm not sure where that ended up. Thank you!! :pray: 💖

**Comment by xiaoya-yaya** [comment]
@ElizabethN I added a new [brand style guide](https://docs.google.com/presentation/d/1BZSBa4Ttji95NTPwHcVjcu-CgiuwBezd/edit#slide=id.p10) page under the **media and outreach** folder and linked this into the document.

The slide link was also added to the [Design contribution guide](https://github.com/chaoss/community/blob/main/how-to-contribute/contributing-to-chaoss/design-contribution.md#design-contribution).

**Comment by ElizabethN** [comment]
Awesome, @xiaoya-yaya! Thank you so much for this! I can finally close this issue I think 😆
