### ISSUE TITLE
Ideas for Projects for She Code Africa

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#302]
CHAOSS is very interested in participating in the April-May cohort of [She Code Africa's Contributhon](https://sites.google.com/shecodeafrica.org/contributhon/mentor-orgs), but before we can complete our application to be a mentor organization, we need to define what project they will be working on. I think this is a little bit different than our usual GSOC projects because of the shorter timing, and the fact that we have a CHAOSS member who is a past participant in this special project. We will hopefully be able to participate as a mentorship organization, but it depends on if the project gets sufficiently funded from sponsorship orgs.

Our current idea is to create a slackbot that would help point newcomers to some resources upon joining our Slack community. 

@ruth-ikegah were you interested in being a mentor for this? It has been a really long time since I wrote a slackbot :laughing: but I could try to help out on the technical side if needed. 

If we think this is a project we want to submit, we will have to draw up a list of subtasks and technical requirements (operating systems, etc).

The application (along with the project and subtasks) is due **February 28**, so we are kind of tight on time. 

Would appreciate any other insights and comments @germonprez and @sgoggins.

**Comment by germonprez** [comment]
Thanks @ElizabethN. This sounds like a great project idea. I'd sort of suggest only 1 (maybe 2) project ideas. The slackbot sounds great and I really liked that idea when it was talked about in the DEI audit team meeting.

**Comment by ElizabethN** [comment]
>Another idea I have for a project, we chatted about graphically representing our CHAOSS metrics (the one in the PDF) which will need design skills.

I really like this idea, too! Is this something you would be able to act as a mentor, @Ruth-ikegah? I think you'd be awesome as a mentor!

**Comment by Ruth-ikegah** [comment]
Yes, I can! We can talk more about it on slack or our 1:1 @ElizabethN

**Comment by ElizabethN** [comment]
OK so after talking about this even more with @germonprez and the DEI Working Group, we think it would be fine to go ahead with our slackbot project idea and have you mentor, @Ruth-ikegah. We have plenty of people who can support from a technical standpoint that we shouldn't have any trouble. We can discuss at our weekly meeting tomorrow @Ruth-ikegah but let's do it! :tada:

**Comment by germonprez** [comment]
Hi all, I'm going to close this issue as the ideas have become actual projects :)
