### ISSUE TITLE
Outreachy Application-Period Engagement: Documentation Inclusivity

### ISSUE THREAD

**Issue by sgoggins** [chaoss/community#311]
1. An overview of the project can be found at #328
2. Install Augur (https://github.com/chaoss/augur) 
3. Show us a screen shot in this issue that you got it installed (include the screen shot as a comment on this issue)
4. Review the existing documentation at: https://oss-augur.readthedocs.io/en/main/
5. Open an issue or PR to improve Augur documentation. You can edit Augur documentation here: https://github.com/chaoss/augur/tree/main/docs
6. Post your achievements back to the Outreachy application

**Comment by jwflory** [comment]
On the admin/mentor side, see two example issues from a Fedora Project Outreachy project ([example 1](https://pagure.io/fedora-commops/fedora-happiness-packets/issue/100), [example 2](https://pagure.io/fedora-commops/fedora-happiness-packets/issue/103)). Including links to helpful documentation and clarifying what "success" looks like is helpful too. For example, a screenshot of what exactly? Should I show it running from the command line, or a GUI? What are the expectations for a newcomer to successfully complete this task?

Related to #312.

**Comment by thesakshidiggikar** [comment]
I need help can I get help plz...for installing augur...?

**Comment by thesakshidiggikar** [comment]
I am facing this issue while installing augur can you plz help out? 
![image](https://user-images.githubusercontent.com/91860781/158078534-5b98ef38-fd4d-4f94-8f7f-edd6c3554175.png)

**Comment by thesakshidiggikar** [comment]
after done with the stet up of backend in PostgreSQL ... I am confused about in next step for next for the setting of the next step that is augur  I  Have clone the request made a local environment in my Visual studio code .....i have this till now

![image](https://user-images.githubusercontent.com/91860781/158139706-4df0743a-481a-4b20-9f6c-0c35933836a9.png)

**Comment by Biki-das** [comment]
@sgoggins what do we mean here by install, like for the documentation inclusivity we need to locally run the doc first in a localhost, test our changes , but I did not find any instruction for the same , am I interpreting something wrong?

**Comment by Preshh0** [comment]
@Biki-das, there's an installation guideline in the docs.

**Comment by marv-tech** [comment]
![AUGUR INSTALLATION](https://user-images.githubusercontent.com/57637620/163578034-6d1bd720-fc34-4357-a5af-868f8afa36f9.png)

Screenshot of Augur installation

**Comment by Francoise02** [comment]
> @Biki-das, there's an installation guideline in the docs.

Hello @Biki-das, I'm also stuck on the installation but I can't see the guide you have mentioned in the docs. Please can you share the exact link to the guide? Thanks in advance :)

**Comment by Preshh0** [comment]
> 

Hi @Francoise02, this is the one I'm currently using https://oss-augur.readthedocs.io/en/main/quick-start.html.

Although it's still proving difficult to install. What OS are you using?

**Comment by Francoise02** [comment]
Hello, @Preshh0 Thank you for sharing. Let me check it out! I'm using Microsoft Windows.

**Comment by namgyalangmo** [comment]
![installss](https://user-images.githubusercontent.com/75657887/164005352-94e65f50-8c17-4f3f-9fef-d71d4954509d.jpeg)

**Comment by Preshh0** [comment]
![augur_success4!](https://user-images.githubusercontent.com/42142405/164022857-93e541b3-0d80-4e97-aa23-071733cab3b2.PNG)

![augur_success2!](https://user-images.githubusercontent.com/42142405/164022871-31046c11-85cc-45dc-8bad-9319b16cdb03.PNG)

**Comment by Biki-das** [comment]
![Capture](https://user-images.githubusercontent.com/72331432/164031385-00cddbc6-0860-44cd-b773-ef685412f60b.PNG)

Augur successfully Installed .

**Comment by yashtikajigs** [comment]
I have used the Docker method to install augur. Below is the snapshot of the same- 
<img width="1440" alt="Screenshot 2022-04-12 at 6 16 16 PM" src="https://user-images.githubusercontent.com/100202374/164206314-64119ef0-0ad0-4426-8fc7-3e2029b8f97b.png">

**Comment by HarrietAkot** [comment]
![Uploading Screenshot from 2022-04-18 11-56-21.png…]()

**Comment by HarrietAkot** [comment]
![Screenshot from 2022-04-18 11-56-21](https://user-images.githubusercontent.com/44574124/164520769-475e29be-689c-4b53-af26-307d8d840ad0.png)

**Comment by Priya730** [comment]
![image](https://user-images.githubusercontent.com/60316903/164537755-576a4ea7-fd91-4517-be32-599eeef3b335.png)

**Comment by DevanshRaizada** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/76863326/164615068-54c4f5ed-529c-4bba-a554-29fc3d097845.png)

**Comment by DevanshRaizada** [comment]
![Screenshot (126)](https://user-images.githubusercontent.com/76863326/164615143-f61167c5-533b-453c-b88a-664adb13b8d5.png)

**Comment by Biki-das** [comment]
> ![Screenshot (126)](https://user-images.githubusercontent.com/76863326/164615143-f61167c5-533b-453c-b88a-664adb13b8d5.png)


hey  @DevanshRaizada you are copying my screenshot and posting it as your work? accidental ? please remove it.

**Comment by DevanshRaizada** [comment]
> > ![Screenshot (126)](https://user-images.githubusercontent.com/76863326/164615143-f61167c5-533b-453c-b88a-664adb13b8d5.png)
> 
> hey @DevanshRaizada you are copying my screenshot and posting it as your work? accidental ? please remove it.

Sorry attached wrong ss by mistake

**Comment by Xaviemille** [comment]
![Augur](https://user-images.githubusercontent.com/39471619/164690997-3eac6f94-01d9-4db8-a17f-3cdd0950ca78.jpeg)

**Comment by Biki-das** [comment]
> > > ![Screenshot (126)](https://user-images.githubusercontent.com/76863326/164615143-f61167c5-533b-453c-b88a-664adb13b8d5.png)
> > 
> > 
> > hey @DevanshRaizada you are copying my screenshot and posting it as your work? accidental ? please remove it.
> 
> Sorry attached wrong ss by mistake

hey @DevanshRaizada plz remove it.

**Comment by germonprez** [comment]
> > > > ![Screenshot (126)](https://user-images.githubusercontent.com/76863326/164615143-f61167c5-533b-453c-b88a-664adb13b8d5.png)
> > > 
> > > 
> > > hey @DevanshRaizada you are copying my screenshot and posting it as your work? accidental ? please remove it.
> > 
> > 
> > Sorry attached wrong ss by mistake
> 
> hey @DevanshRaizada plz remove it.

Has this been resolved?

**Comment by Delight362** [comment]
![Screenshot from 2022-04-22 13-19-05](https://user-images.githubusercontent.com/96892410/164713700-caf278ca-f71e-48f0-b923-f5a74a4acf2d.png)

**Comment by fakeInsights** [comment]
Hello All,
This Augur running on Google Colab.  Any thoughts and feedback are welcome. Thanks -- 
This is the start of a PR to improve Augur documentation and broaden inclusivity through a demo that works on Google Colab, a tool that is widely available for free online.

![augur01](https://user-images.githubusercontent.com/4354246/164739816-32f3d708-5e45-4dc9-ae45-0fd960183e87.jpg)
![augur02](https://user-images.githubusercontent.com/4354246/164739811-c607a386-c0ad-4bb0-bbe8-93d00fe2efec.jpg)
![augur03](https://user-images.githubusercontent.com/4354246/164739875-9f203c1e-9f66-41ab-b92f-8b4bff9a6162.jpg)
![augur04](https://user-images.githubusercontent.com/4354246/164739806-4520a539-43a6-468b-ab48-be7c9282ec2a.jpg)
![augur05](https://user-images.githubusercontent.com/4354246/164739799-1b31b3c2-d8d2-4b8b-9a13-caee3ae471d3.jpg)
![augur06](https://user-images.githubusercontent.com/4354246/164739867-4af5eff8-ecb7-4f58-b5fd-d8afc3e4fd1c.jpg)
![augur07](https://user-images.githubusercontent.com/4354246/164739862-788c16ad-155f-4e40-bde5-3022db3b1d58.jpg)
![augur08](https://user-images.githubusercontent.com/4354246/164739853-65bf084a-b5fd-4c5d-a7fe-47e934b61a9c.jpg)
![augur09](https://user-images.githubusercontent.com/4354246/164739839-9a934719-2ca2-4be2-a1d9-4e858da131f8.jpg)
![augur10](https://user-images.githubusercontent.com/4354246/164739831-f69c17d0-f302-496b-82c8-96dbed9055e2.jpg)
![augur11](https://user-images.githubusercontent.com/4354246/164739825-f5ad54b1-244a-4cbb-b14d-bca09ca65322.jpg)

**Comment by ElizabethN** [comment]
I'm going to close this issue now that the Outreachy deadline has passed.
