### ISSUE TITLE
Outreachy Application-Period Enagement: Conversion Rate

### ISSUE THREAD

**Issue by sgoggins** [chaoss/community#312]
1. An overview of the project can be found at #310 
2. Install Grimoirelab (https://github.com/chaoss/grimoirelab)
3. Create a screen shot of your installed Grimoirelab instance and paste it as a comment in this issue. 
4. Post an issue (not a PR) in the Metrics Model Working Group Repository (https://github.com/chaoss/wg-metrics-models)
5. The issue should include 1) Your Name, 2) A description of how you think you would deploy the metrics model in GrimoireLab. Be descriptive in your explanation - including such things as data sources, data aggregation, and visualizations.
6. Post your achievements back to the Outreachy application

**Comment by fernanda-ordonez** [comment]
Hello everyone! Here is my first issue :) 
<img width="1235" alt="Fernanda_first_issue" src="https://user-images.githubusercontent.com/66924998/160520266-87bdf44d-bd92-411b-9315-d5cefcbae93e.png">

**Comment by yashtikajigs** [comment]
Dear Community,  I am Yashtika Jigyasu. I am an applicant for the Outreachy Internship. As per instruction in #2 of this issue, I have installed Grimoirelab on my local laptop using Docker. 
Steps I followed- 
Clone this project:
$ `git clone https://github.com/chaoss/grimoirelab`
Go to docker-compose folder and run the following command:
$ `cd grimoirelab/docker-compose`
$ `docker-compose up -d`
Then I visited http://localhost:5601 in my browser.

Below is the snapshot-  
![Overview-GrimoireLab-Dashboard](https://user-images.githubusercontent.com/100202374/163391986-42de8867-ac95-487f-a185-0f5506d49651.png)

**Comment by thushariii** [comment]
Hello mentor! I am Thushari From Sri Lanka. I believe I am a bit late to join in. When I went through Chaoss and Grimorelab repositories It really excited me to contribute to this project and I appreciate the notion of the organization. Please find the snapshot of my Grimoirelab instance. I also tried to make some visualizations and my observation was that it takes a long time to generate certain complex visualizations. I believe there must be a way around this. Since I am new to the project I would appreciate it If you can elaborate on the criteria/ aspects you expect in the description of how to deploy the metrics model.  This visualization shows the two nodes (repository and labels) network connection for github_issues.
![image](https://user-images.githubusercontent.com/55043879/163653565-7a2efd04-edf0-4e2d-96fa-a4d85450ab86.png)

**Comment by germonprez** [comment]
> Hello mentor! I am Thushari From Sri Lanka. I believe I am a bit late to join in. When I went through Chaoss and Grimorelab repositories It really excited me to contribute to this project and I appreciate the notion of the organization. Please find the snapshot of my Grimoirelab instance. I also tried to make some visualizations and my observation was that it takes a long time to generate certain complex visualizations. I believe there must be a way around this. Since I am new to the project I would appreciate it If you can elaborate on the criteria/ aspects you expect in the description of how to deploy the metrics model. This visualization shows the two nodes (repository and labels) network connection for github_issues. ![image](https://user-images.githubusercontent.com/55043879/163653565-7a2efd04-edf0-4e2d-96fa-a4d85450ab86.png)

Thanks for this Thushari. I'm tagging @sduenas and @GeorgLink who might be able to provide some great advice here.

**Comment by GeorgLink** [comment]
Hi @thushariii, 

Welcome to CHAOSS and thank you for your interest in working on this.

> I also tried to make some visualizations and my observation was that it takes a long time to generate certain complex visualizations. I believe there must be a way around this.

Are you experiencing slowness from the dashboard displaying a visualization? This would required more hardware resources to process faster.

Are you experiencing slowness in figuring out how to create meaningful visualizations? This gets better with practice, [making visualizations in Kibana](https://chaoss.github.io/grimoirelab-tutorial/docs/dashboards/visualization/) and [understanding the data schema](https://chaoss.github.io/grimoirelab-tutorial/docs/data-sources/schema/). 

> I would appreciate it If you can elaborate on the criteria/ aspects you expect in the description of how to deploy the metrics model.

Each metrics model has a list of metrics. For example, the [Issues Handling](https://github.com/chaoss/wg-metrics-models/blob/main/focus-areas/development/metric-model-issue-handling.md) metrics model includes the metric [Issues New](https://chaoss.community/metric-issues-new/). What I would find helpful is a description for each metric about how to visualize it in GrimoireLab. 

To describe a visualization in GrimoireLab, we need the following information (several are visible from your screenshot):

* Visualization type - How is the data displayed? Chosing the visualization type is the first step when creating a visualization.
* Index - Where is the data coming from? Chosing the index is the second step when creating a visualization.
* Fields and their configurations 
* Buckets and their configuration
* Filters and their configuration

**Comment by kaitlyncodesthings** [comment]
Hello! My name is Kaitlyn, and I'm an Outreachy internship applicant. After a few hours of extreme technical difficulties (and having to start over twice), I've managed to get Grimoire Lab installed on to my desktop using Docker and following the instructions list above. 

Below is my screenshot of the link once everything is up and running: 
![screenshot-localhost_5601-2022 04 22-11_26_13](https://user-images.githubusercontent.com/96637219/164746486-90f5f8e7-52f6-4db4-b9ab-33a8e20ce636.png)

**Comment by ElizabethN** [comment]
I'm closing this issue, as the Outreachy deadline has passed.
