### ISSUE TITLE
Newcomer opportunity: Chair a CHAOSS Working Group meeting

### ISSUE THREAD

**Issue by jwflory** [chaoss/community#318]
# Summary

Create more opportunities for someone to chair a meeting by requesting coaching or mentorship in advance.

# Background

I like that the Fedora Project gives a [virtual badge](https://badges.fedoraproject.org/badge/secretary-general) to a contributor for chairing a team meeting. Acknowledging it with a small token of appreciation incentivizes participation and empowers new contributors to gradually become more engaged in the community.

I thought it could be helpful to give long-time WG meeting conveners a break, and a chance for them to become mentors by helping others chair working group meetings. 

# Details

I could see a couple of ways of this working:

1. Create a weekly/fortnightly "meeting chair coaching" session, as an alternative to office hours.
2. Create an asynchronous form for someone to declare interest in chairing a meeting, but request guidance and coaching on how best to go about it.
3. Mix of the above.

I think this could tie in nicely with the ongoing efforts to improve the newcomer experience. It would also likely require coordination with each working group. Could meeting chair mentorship be generalized for any working group?

# Outcome

Lower barrier for new volunteers for chairing a working group meeting.

**Comment by ElizabethN** [comment]
I think this is an excellent idea, @jwflory! Dropping a few supporting pieces of info for reference. 
- The option to facilitate a meeting is on our [newcomer form](https://docs.google.com/forms/d/e/1FAIpQLSd2-JGEYYLl9ZOgpPxL7ihvW-9kvzfTxgIpuyXfxLizbyIi1A/viewform) (but not everyone sees this or chooses to fill this out)
- We have [written guidance on how to facilitate a meeting](https://docs.google.com/document/d/1fCxgKXmvASZ2OQA3Eu9OqlzuFSdPtNZHInJHYr0vF8g/edit) that would be helpful for someone interested in doing this.
- We actively rotate meeting facilitation in the DEI Working Group and DEI Badging meetings but I think they are the only ones.

**Comment by Preshh0** [comment]
Hi, I'd like to be assigned this. I've already filled out the form in the link given above and read through the guidelines. If there's anything extra expected of me to be able to chair, I'd like to know. 
Ps: I'm an Outreachy applicant. 
Cheers.

**Comment by ElizabethN** [comment]
Hi @Preshh0! Thanks for reaching out. It would be a good idea to attend a few meetings so you know what they are like, before facilitating. We rotate facilitation in our DEI Badging Meeting and our DEI Working Group meetings, which would be a great place to start. You can see details of when these meetings happen and how to join, on our [Participate Page](https://chaoss.community/participate). Hope that helps!

**Comment by Preshh0** [comment]
Yes it does. And I will, thank you for taking time out to reply me!

**Comment by ElizabethN** [comment]
We now have some documentation on how to facilitate a meeting, and this is listed under the newcomer information. I'm going to close this issue as completed :+1:
