### ISSUE TITLE
CHAOSS website is down

### ISSUE THREAD

**Issue by yashtikajigs** [chaoss/community#338]
Dear community, I am an initial applicant for Outreachy. I am potentially looking for an opportunity to contribute at CHAOSS and hence I have been going through several documents. I have found that CHAOSS website's URL - https://chaoss.community/ has been referenced at various locations but when I tried to visit this URL, the site is down. Seems like this is a hosting-related issue. 
Please look at attached snapshot below-
![chaoss](https://user-images.githubusercontent.com/100202374/162572559-e9801784-c5e2-4b5b-88b2-3399dec0ee6d.png)

**Comment by yash2002109** [comment]
Thanks for pointing this out, I guess @klumb can look into it.

**Comment by klumb** [comment]
Thanks @yashtikajigs @yash2002109

The site is back up now.
