### ISSUE TITLE
Google Season of Docs: TODOs for Application

### ISSUE THREAD

**Issue by germonprez** [chaoss/community#354]
All proposals are submitted to our [Interest Page](https://github.com/chaoss/community/blob/main/GSoD-interest.md)
- You do not need to submit a proposal to all of the potential topics. Just pick one and submit your proposal, clearly defining what topic you are interest in. Three available topics are listed below. 

## Website and Metrics Release
- Task - Audit documents on how to contribute to the website. This would include compiling all of the documents related to website contribution into a folder in the community handbook (in a forked repo). This would also include the creation of a website contribution readme that would link to relevant documents. The proposal document should include recommendations for; (1) streamlining the contribution process, (2) edits to existing documents, and (3) creating any missing documentation.
- Task - Audit documents on metrics release, review, and revision. This would include compiling all of the documents related to the release, review, and revision of metrics into a folder in the community handbook (in a forked repo). This would also include the creation of metrics release readme that would link to all relevant documents. The proposal document should include recommendations for; (1) streamlining the release, review, and revision process, (2) edits to existing documents, and (3) creating any missing documentation.

## Community Handbook
- Task - Link to an example of documentation you have created or edited in the past. (It does not have to be technical in nature, but it should be instructional). Please explain your role in the creation of the document and the process you used when creating or editing the document.
- Task - Link to three examples of open source project documentation and write a critique of each one. What do you like about them? What would you change? Do you think they are effective? Why or why not? How easy was it for you to find and navigate through them?
- Task - Explain the role of a community handbook in an open source project. Include what you think the goals of a community handbook are, who the audience is, topics that should be covered, and why a community would want to implement one. 
- Task - Find the current CHAOSS Community Handbook and answer the following questions, if you are able to find the answer. If you can’t find the answer to the question, document the process you took to look for the answer.
-- Who is on the CHAOSS governing board?
-- How do I join a CHAOSS meeting?
-- What does the Value Working Group work on?
-- What is the CHAOSS definition of “core contributor”?

# Augur
- Task - Link to an example of documentation you have created or edited in the past. (It does not have to be technical in nature, but it should be instructional). Please explain your role in the creation of the document and the process you used when creating or editing the document.
- Task - Link to three examples of open source project documentation and write a critique of each one. What do you like about them? What would you change? Do you think they are effective? Why or why not? How easy was it for you to find and navigate through them?
- Task - Install Augur following our existing documentation, and make suggestions for changes via either opening an issue, or making a Pull Request to update the documentation.

**Comment by pratik2315** [comment]
Thanks for the information @germonprez ! 
Looking forward to learn and interact with the Chaoss community in Google season of docs 2022.

**Comment by skdbsp123** [comment]
Hello @germonprez 

I am planning to contribute to the task

> Task - Audit documents on how to contribute to the website. This would include compiling all of the documents related to website contribution into a folder in the community handbook (in a forked repo). This would also include the creation of a website contribution readme that would link to relevant documents. The proposal document should include recommendations for; (1) streamlining the contribution process, (2) edits to existing documents, and (3) creating any missing documentation.

Can you suggest a good starting point to know more about the community and other info that will help me write my proposal.

**Comment by germonprez** [comment]
Hi @skdbsp123 are you able to join the CHAOSS Community Call? It is on Tuesdays at 11am US Central.

**Comment by skdbsp123** [comment]
> Hi @skdbsp123 are you able to join the CHAOSS Community Call? It is on Tuesdays at 11am US Central.

Sure, I'll join the call
