### ISSUE TITLE
[DISCOURSE] Create a list of initial tags

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#466]
Instead of creating sub categories for all the working groups and topics, we thought it would be better to use tagging to separate these conversations. 

We need to create a list of initial tags we want folks to use. Things that would be on this list include: 

- working group names (in a #wg-name format)
- CHAOSS initiatives (like dei event badging, badging website, newcomer slack bot)
- #metrics
- #metrics-models
- software (#augur #grimoirelab) 
- #chaosscon

I created a [Google Doc](https://docs.google.com/document/d/1pD0HF3mxyKOm1E2jDANbdywkRp8_jV_-0XeElWGeBzw/edit#) where we can collaborate on this list.

**Comment by j-enny** [comment]
I am working on this issue

**Comment by BhaswatiRoy** [comment]
Hello @ElizabethN 
This list can be added to the "New Contributors" section of the Community page. Since this part already contains info regarding slack, so we can just add the list there for people to start. 
I can work on this
![image](https://user-images.githubusercontent.com/78029145/212547166-458ac5e5-83a2-4493-ab14-d5f4d39af81e.png)

**Comment by ElizabethN** [comment]
Hmm, I think this list will exist only on Discourse as a way to categorize the discussions there. Can you tell me more about how it would fit in with our quick start guide?

**Comment by ElizabethN** [comment]
@BhaswatiRoy ohhhh now I understand! I think we want to keep this Quickstart document super simple and lightweight, so let's add the tag information to a new document called "Getting Started with Discourse" that we can use when people sign up. What do you think?

**Comment by ElizabethN** [comment]
Maybe we should put that list in one of these documents: https://github.com/chaoss/community/issues/492?

**Comment by BhaswatiRoy** [comment]
Yes that name sounds good and I can work on this!

**Comment by ElizabethN** [comment]
I've added these tags into Discourse, so Im' closing this issue. ✨
