### ISSUE TITLE
[DISCOURSE] Moderation Guide

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#467]
We need to have a moderation guide for our team of moderators for this forum. It would be great to draw on inspiration from other communities. 

Some initial places we can look (from @jwflory - THANK YOU!)

- Fedora CoC: [Clarifying notes and statements](https://docs.fedoraproject.org/en-US/project/coc-clarifying/)
- Fedora’s efforts on [moderation guidelines](https://pagure.io/ModeratorGuidelines/tree/master)
- SpigotMC moderation approach for >150k teenagers
- JWF/internal: [Staff Handbook](https://www.dropbox.com/s/jehzwmw55e35k6n/Staff%20Handbook.pdf?dl=0), [Discipline Policy](https://www.dropbox.com/s/y44seqwyxxhdc8a/Discipline%20Policy.pdf?dl=0)

Are there other communities that provide a great set of guidelines for their moderation team? It would be great if we had other ideas here in this issue. 

Action Items: 
- [ ] Compile list of other communities' guidelines
- [ ] create a draft that pulls inspiration
- [ ] get feedback from the team working on this implementation

**Comment by j-enny** [comment]
Here is a list of guidelines I gathered

- O.S.C.A - [Code of Conduct](https://docs.oscafrica.org/about/community-code-of-conduct)
- Apache Open Office - [Moderator Code of Conduct](https://forum.openoffice.org/en/forum/viewtopic.php?t=12535)
- FOSDEM - [Code of Conduct](https://fosdem.org/2023/practical/conduct/)
- Moodle - [Moderator Guide](https://docs.moodle.org/401/en/Moderator_guide)
- Gnome - [Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)
- Eclipse Foundation - [Code of Conduct](https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php)

**Comment by ElizabethN** [comment]
@j-enny thank you so much! These are super helpful!

**Comment by ElizabethN** [comment]
After reading through these extra resources, I think CHAOSS will initially use the official [Discourse Moderation Guide.](https://meta.discourse.org/t/discourse-moderation-guide/63116). Not only is it a comprehensive guide for best practices in moderating forums, because it's tailored specifically for Discourse, it shows how to implement the suggested actions (flagging posts, editing posts, banning users, etc).
