### ISSUE TITLE
[DISCOURSE] Determine Initial Set of Badges

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#468]
I'm honestly not a huge fan of the initial set of badges that come with the default Discourse implementation. They are: 
Badges

- [Licensed](https://chaoss.discourse.group/admin/badges/101)
- [Autobiographer](https://chaoss.discourse.group/admin/badges/9)
- [Certified](https://chaoss.discourse.group/admin/badges/100)
- [Editor](https://chaoss.discourse.group/admin/badges/10)
- [First Emoji](https://chaoss.discourse.group/admin/badges/41)
- [First Flag](https://chaoss.discourse.group/admin/badges/13)
- [First Like](https://chaoss.discourse.group/admin/badges/11)
- [First Link](https://chaoss.discourse.group/admin/badges/14)
- [First Mention](https://chaoss.discourse.group/admin/badges/40)
- [First Onebox](https://chaoss.discourse.group/admin/badges/42)
- [First Quote](https://chaoss.discourse.group/admin/badges/15)
- [First Reaction](https://chaoss.discourse.group/admin/badges/102)
- [First Reply By Email](https://chaoss.discourse.group/admin/badges/43)
- [First Share](https://chaoss.discourse.group/admin/badges/12)
- [New User of the Month](https://chaoss.discourse.group/admin/badges/44)
- [Reader](https://chaoss.discourse.group/admin/badges/17)
- [Read Guidelines](https://chaoss.discourse.group/admin/badges/16)
- [Wiki Editor](https://chaoss.discourse.group/admin/badges/48)
- [Admired](https://chaoss.discourse.group/admin/badges/31)
- [Champion](https://chaoss.discourse.group/admin/badges/27)
- [Crazy in Love](https://chaoss.discourse.group/admin/badges/35)
- [Devotee](https://chaoss.discourse.group/admin/badges/47)
- [Empathetic](https://chaoss.discourse.group/admin/badges/39)
- [Great Share](https://chaoss.discourse.group/admin/badges/23)
- [Know-it-All](https://chaoss.discourse.group/admin/badges/105)
- [Solution Institution](https://chaoss.discourse.group/admin/badges/106)
- [Aficionado](https://chaoss.discourse.group/admin/badges/46)
- [Anniversary](https://chaoss.discourse.group/admin/badges/24)
- [Campaigner](https://chaoss.discourse.group/admin/badges/26)
- [Gives Back](https://chaoss.discourse.group/admin/badges/32)
- [Good Share](https://chaoss.discourse.group/admin/badges/22)
- [Higher Love](https://chaoss.discourse.group/admin/badges/34)
- [Respected](https://chaoss.discourse.group/admin/badges/37)
- [Guidance Counsellor](https://chaoss.discourse.group/admin/badges/104)
- [Appreciated](https://chaoss.discourse.group/admin/badges/36)
- [Enthusiast](https://chaoss.discourse.group/admin/badges/45)
- [Nice Share](https://chaoss.discourse.group/admin/badges/21)
- [Out of Love](https://chaoss.discourse.group/admin/badges/33)
- [Promoter](https://chaoss.discourse.group/admin/badges/25)
- [Solved!](https://chaoss.discourse.group/admin/badges/103)
- [Thank You](https://chaoss.discourse.group/admin/badges/38)
- [Welcome](https://chaoss.discourse.group/admin/badges/5)
- [Famous Link](https://chaoss.discourse.group/admin/badges/30)
- [Great Reply](https://chaoss.discourse.group/admin/badges/8)
- [Great Topic](https://chaoss.discourse.group/admin/badges/20)
- [Good Reply](https://chaoss.discourse.group/admin/badges/7)
- [Good Topic](https://chaoss.discourse.group/admin/badges/19)
- [Hot Link](https://chaoss.discourse.group/admin/badges/29)
- [Nice Reply](https://chaoss.discourse.group/admin/badges/6)
- [Nice Topic](https://chaoss.discourse.group/admin/badges/18)
- [Popular Link](https://chaoss.discourse.group/admin/badges/28)
- [Leader](https://chaoss.discourse.group/admin/badges/4)
- [Regular](https://chaoss.discourse.group/admin/badges/3)
- [Basic](https://chaoss.discourse.group/admin/badges/1)
- [Member](https://chaoss.discourse.group/admin/badges/2)

I feel like we could make these more CHAOSS-y. What badges would we want to remove? What badges do we want to create?

**Comment by kaxada** [comment]
Pretty long list... You wanna add some or overhaul the whole badges to make them 'chaotic'?

**Comment by sgoggins** [comment]
how are the badges assigned/granted?

**Comment by ElizabethN** [comment]
These are the badges I'm going to propose: 

- Autobiographer (for filling out your profile and uploading an avatar)
- Admired (get 5 likes on 300 posts)
- Champion (invite 5 members)
- Aficionado (visits every day for 100 days in a row)
- Daily Supporter (visits every day for 365 days in a row)
- Anniversary (visited at least once during the year)
- Appreciated (received 2 likes on at least 20 posts)
- Enthusiast (visited every day for 10 days)
- Welcome (received your first like)
- Nice Topic (received 10 likes on your first topic)
- Nice Reply (received 10 likes on your first reply)
- Great Topic (received 50 likes on your first topic)
- Great Reply (received 50 likes on your first reply)
- New Chaotic (Trust Level 1)
- Active Chaotic (Trust Level 2)
- Enthusiastic Chaotic (Trust Level 3)
- Core Chaotic (Trust Level 4)

**Comment by ElizabethN** [comment]
I didn't get any negative feedback on this, so this is what we're starting with anyway! We will see how it goes. :blush:
