### ISSUE TITLE
[Proposal] Align the discussions between OSPOlogy APAC and CHAOSS APAC

### ISSUE THREAD

**Issue by xiaoya-yaya** [chaoss/community#471]
## Background
 
Quite a few CHAOSS AP members are of the background of company OSPOers and looking for measurement solutions for their company. CHAOSS has set up the [OSPO working group](https://github.com/chaoss/wg-ospo) and is an OSPO associate of the TODO group.

Currently, we have the AP calls in both communities and similar discussions raised from time to time, however, there are no channels to promote further communications and integrate the output.

## Goal

Align the discussions between CHAOSS APAC and OSPOlogy APAC calls. 

## Proposed Actions

**From 2023, we might**:
- Switch CHAOSS APAC to a Monthly call, at the same time of day as with the OSPOlogy call
- Alternate CHAOSS APAC call and OSPOlogy every two weeks. OSPOlogy APAC calls will focus on how to address context on OSPO sustainability and continuity and CHAOSS APAC calls on how to develop questions and metrics under such context.
- Create events on both community’s meeting calendar
- Promote meetings in Slack channels #chaossaisa, #chapter-apac, #wg-ospometrics-chaoss, etc 
- Record the meeting notes through one uniform document
- Use #wg-ospometrics-chaoss for a common point of communication with the global OSPO WG meetings and APAC CHAOSS and OSPOlogy 

## Expectations
Involve people from both CHAOSS and TODO Group to communicate OSPO-related metrics in the ASIA-PACIFIC region
Output OSPO metrics for OSPO sustainability and continuity in ASIA-PACIFIC orgs

## Deadline

If there is no opposition to this by SC or the community, we will implement these changes starting on Jan 1st, 2023

**Comment by xiaoya-yaya** [comment]
Hi community! This proposal has also been raised here: https://github.com/todogroup/ospology/discussions/221

We'd like to get the review, comments, and support from both CHAOSS and TODO Group communities.

**Comment by germonprez** [comment]
Thanks for sharing this @xiaoya-yaya -- I really appreciate the effort to draw these two communities together. I'm all for finding the common ground, as you have suggested.

**Comment by xiaoya-yaya** [comment]
The changes have been implemented starting from January 2023.

**Comment by xiaoya-yaya** [comment]
Starting in 2023,

**The CHAOSS AP meeting is** 
- a monthly call on the second Monday of the month, 3pm UTC+8
- https://zoom.us/j/4998687533

**The OSPOlogy AP call is**
- a monthly call on the last Monday of the month, 3pm UTC+8
- [https://zoom.us/j/94118189380?pwd=YTJIZUU2WVd3R2d2c044eUVXZWhOZz09](https://www.google.com/url?q=https://zoom.us/j/94118189380?pwd%3DYTJIZUU2WVd3R2d2c044eUVXZWhOZz09&sa=D&source=calendar&usd=2&usg=AOvVaw33dsq87AGlCl04PV_BUigu)
