### ISSUE TITLE
Fix links to images

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#475]
Hi! In order for the images to display properly on the CHAOSS website, we will need to make all the links in the [design contribution document](https://github.com/chaoss/community/blob/main/how-to-contribute/design-contribution.md) full URL paths. (They are relative links right now.)

This would be a great issue for a first time contributor! :blush:

**Comment by SainiAditya1** [comment]
@ElizabethN . please close this issue as it is completed.

**Comment by ElizabethN** [comment]
:+1: will do!
