### ISSUE TITLE
[Proposal] Building a community handbook collaboration bot

### ISSUE THREAD

**Issue by xiaoya-yaya** [chaoss/community#477]
Hi community, when @Ruth-ikegah and I  were maintaining the handbook as technical writers for CHAOSS, we came up with the idea of building a collaboration bot to:

- collect updating areas from multiple channels (community calls, slack, etc)
- open (bi-)monthly tickets to collect and track the updates
- sync the content from GitHub to the website

This might potentially be saved as a GSoC idea, if feasible.

**Comment by germonprez** [comment]
Thanks @xiaoya-yaya -- I'm going to repost this in Slack if someone is interested.

**Comment by Namyalg** [comment]
Hey @xiaoya-yaya, I am interested in working on this issue.

**Comment by germonprez** [comment]
Thanks for you interest @Namyalg -- also pinging @Ruth-ikegah here too.

**Comment by Ruth-ikegah** [comment]
Sure, @Namyalg, I will go ahead and assign this issue to you! Feel free to share your plan for building the bot with us through the comments or a google doc.

Feel free to ask any questions.

**Comment by Namyalg** [comment]
Yes, I will share my ideas.

**Comment by Namyalg** [comment]
Hey @all, sharing a document containing a high-level understanding of the requirements along with some questions I had : https://docs.google.com/document/d/1U2Bt624QtLSEbkzyKmUzl9aZ2ZU73YDrcHmxDolvzF4/edit?usp=sharing

**Comment by Ruth-ikegah** [comment]
Hi @Namyalg, well done on this! I have responded to your questions in the doc. Will you be available to join our weekly meeting tomorrow by 11 am Central time? So we can get more feedback from the community?

Adding @ElizabethN, our SUPER Community Manager, to this thread to give feedback too!

**Comment by Namyalg** [comment]
Yes, thank you for the feedback!
I will attend the weekly call

**Comment by germonprez** [comment]
@Namyalg and @Ruth-ikegah -- do you have any interest or updates on this Issue?

**Comment by ElizabethN** [comment]
I'm going to go ahead and close this issue. We can always re-open if we have folks interested in pursuing this!
