### ISSUE TITLE
Change Meeting time for CHAOSS Asia Pacific Community

### ISSUE THREAD

**Issue by Ruth-ikegah** [chaoss/community#483]
Problem: The Asia Pacific community recently changed their meeting time from "bi-weekly meetings on Wednesdays at 21PM CST" to "2nd Monday of the month at 3 pm UTC +8"

Solution: Check [this file](https://github.com/chaoss/community/blob/main/local-chapters/chaoss-asia.md) and update the text

Need any help, ping @Ruth-ikegah or @ElizabethN if you have any questions! 

Thank you for contributing.

**Comment by xiaoya-yaya** [comment]
Hi @ShreyanshKeshav33 Thanks for your interest! This issue has been assigned to you.
