### ISSUE TITLE
Add information about DCO for newcomers

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#485]
We need to add a section about installing and using the [GitHub DCO plugin](https://github.com/apps/dco) for newcomers. Having a DCO in place is a requirement for all LF Projects (CHAOSS included). Currently we get 0 results in our knowledgebase for a search for this. 

Would someone like to add this to the "[How to contribute](https://github.com/chaoss/community/blob/main/how-to-contribute/README.md)" document?

**Comment by MauryaRitesh** [comment]
Hi, I would like to work on this issue.

**Comment by SainiAditya1** [comment]
hi @ElizabethN can I work on this as I also face this  problem but now , I got this.
