### ISSUE TITLE
Make 0 search results more explicit

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#487]
This is mostly a placeholder for me to look at the Minerva KB Wordpress plugin we are using to see if we can make it more explicit if there are zero search results returned. Right now it just looks like the query didn't go through or that the webpage stopped responding. It just shows a very dim "0 results" in the search bar itself, like this: 

![Screen Shot 2023-01-10 at 11 20 11 AM](https://user-images.githubusercontent.com/57594/211606824-df673968-3b61-43f7-ba7a-10c4729b96b6.png)

**Comment by ElizabethN** [comment]
I spent a long time digging into this today, and I can't find where we can change this. I'll keep looking. In the meantime I did clarify the search tip to try and help this problem.

**Comment by germonprez** [comment]
@ElizabethN -- do you know if there is a solution for this? Should this issue remain open?

**Comment by ElizabethN** [comment]
We have modified how search works and looks on the site, so I'm going to close this. I think it's been taken care of! :tada:
