### ISSUE TITLE
[DISCOURSE] Initial FAQ, Terms of Service, Privacy Policy

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#492]
Unless folks have strong opinions about this, I was going to go with the default Discourse Documents:

 - [FAQ / Expectations for Behavior](https://chaoss.discourse.group/faq)
 - [Terms of Service](https://chaoss.discourse.group/tos) 
 - [Privacy Policy](https://chaoss.discourse.group/privacy)

These documents are related to things like our Code of Conduct, but they are very specific to forum interaction and posting, so they cover things our Code of Conduct might not.

**Comment by Adityasaini10012001** [comment]
@ElizabethN  please assign this to me.

**Comment by ElizabethN** [comment]
@Adityasaini10012001 :wave: HI! There really isn't much to do here, turns out. We are going to use the default discourse docs for now.
