### ISSUE TITLE
Add Design file link and fix broken link on Media-and-outreach folder

### ISSUE THREAD

**Issue by Ruth-ikegah** [chaoss/community#494]
Problem: There is no section for Design files in the [Brand Style guide document](https://github.com/chaoss/community/blob/main/media-and-outreach/brand-style-guide.md), and there is also a broken link on "logos"

Solution: 

1. Add a short section for Design files under "Project Name and Logos" pointing to this drive link: https://drive.google.com/drive/folders/1Ew4EEKmX5A4-4xjgSWvX-g1NwLKM-4s6?usp=sharing
2. Change the broken link to point to this link: https://github.com/chaoss/website/tree/main/About/Media

If you have any questions, feel free to ask @Ruth-ikegah

**Comment by LamiWilliams** [comment]
Hi @Ruth-ikegah Please, assign this to me

**Comment by Ruth-ikegah** [comment]
sure! I just assigned it to you @LamiWilliams

**Comment by Adityasaini10012001** [comment]
Hi @LamiWilliams are you working on this issue..

**Comment by LamiWilliams** [comment]
Hello @Adityasaini10012001 Yes, I am
