### ISSUE TITLE
Limiting the use of acronyms/abbreviations across board on chaoss spaces

### ISSUE THREAD

**Issue by FeazUI** [chaoss/community#505]
# Summary
Limiting the use of complex acronyms/abbreviations to where technically necessary across all chaoss webpages, repositories, meeting minutes, Documentation, Google docs, spreadsheets and the standard naming convention document. 

# Background
For clarity; considering newcomers, open source enthusiasts and for posterity sake. Abiding by the "keep it stupid simple" (KISS) design principle.

# Details
I recommend this be implemented across board, on the website, GIT repositories, Google docs and spreadsheets and also on the naming convention template for future records.

# Outcome
Enabling new and incoming contributors have an easier experience reading, understanding and participating in chaoss documentation and work flow and at large, our great community.

**Comment by FeazUI** [comment]
ok Elizabeth...got it. I'm on it.

**Comment by FeazUI** [comment]
1.
![image](https://user-images.githubusercontent.com/90578264/216460797-09f8e34f-065e-453c-95c1-d024650411f3.jpeg)

The use of CHAOSS under the header “welcome” should be expanded in full form as an introduction on the first page into the chaoss world. 

Also the use of DEI event badging program  acronym in the “finding your way” header, number three. 

https://github.com/chaoss


2.
![image](https://user-images.githubusercontent.com/90578264/216461003-1f455662-57d4-4051-8c76-b64aa99f1314.jpeg)

The Use of PR as an acronym here. 
Typo in the spelling of “Confirming” in second paragraph. 

https://github.com/chaoss/community/blob/main/how-to-contribute/DCOsetup.md


3.
![image](https://user-images.githubusercontent.com/90578264/216461107-e55f3426-c7ab-4cca-84f1-94c978418448.jpeg)

The Use of the Ospo acronym under “Types of Working groups”.

https://github.com/chaoss/community/blob/main/community-initiatives-and-working-groups/Working-Groups/README.md


4.
![image](https://user-images.githubusercontent.com/90578264/216461309-bcc4546b-1b80-4f07-b3ae-10bfb3f64e75.jpeg)

I think we should excalate this terminology-usage.md document, expanded upon and set on front stage. (Pinned to chaoss GitHub repo) So it can be a guiding handbook/ recommended read for chaotics.

https://github.com/chaoss/community/blob/main/community-resources/terminology/terminology-usage.md

**Comment by ElizabethN** [comment]
@FeazUI would you feel comfortable submitting PRs for these changes to these files?

**Comment by FeazUI** [comment]
Absolutely! On it.

**Comment by ElizabethN** [comment]
@FeazUI I was also wondering if it would be helpful to surface these documents on CHAOSS terminology a little better. We have the repo https://github.com/chaoss/community/tree/main/community-resources/terminology but also on the website https://chaoss.community/kbtopic/terminology/. Is there a better way we can make this information discoverable?

**Comment by FeazUI** [comment]
Definitely @ElizabethN, we could add a comprehensive everyday technical terms to the document and pin it front stage on the CHAOSS main repo. 

This process will of course be open to contributions from all chaotics and peer reviewed there after on a google doc.

**Comment by germonprez** [comment]
Hi @FeazUI -- could you provide a few pull requests to suggest some changes that you are mentioning here? I think this is really great, so thanks for the input.

**Comment by FeazUI** [comment]
Hello @germonprez, 
Over time, our great organization has organically implemented those changes to make markdown documents more readable & understandable especially for new chaotics...by way of reducing acronyms and extremely technical terms. 
I will however create a Pull Request for new Markdown documents I think needs a review or some changes 

Cheers!

**Comment by ElizabethN** [comment]
I'm going to go ahead and close this, only because it's really old, and this seems like an ongoing maintenance kind of issue 😄. Happy to merge in any PRs you create to cut down on the abbreviations, @FeazUI!
