### ISSUE TITLE
Metrics template: reviewed on line

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/community#516]
The current metrics template has this line:

> This metric was last reviewed on [date] as part of [ release version] [or recurring review process]

I'm never quite sure what to do with it because we don't really do release versions anymore. Should it be something more like:

> This metric was last reviewed on [date] [for initial release] [or as part of the recurring review process]

**Comment by germonprez** [comment]
I agree with this. I'd also like to move the implementation disclaimer to the bottom of the metric. It would still be present but would keep the description of the metric more connected.

**Comment by klumb** [comment]
I agree on both

**Comment by germonprez** [comment]
Completed.
