### ISSUE TITLE
Data Use Statement: Missing Links

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#523]
Somewhere along the way the links in our Data Use Statement got removed under the Privacy: Published Guidance section. 

https://github.com/chaoss/community/blob/main/data-use-statement.md

**Comment by CBID2** [comment]
Hi @ElizabethN! :) Can I work on this issue? 😊

**Comment by germonprez** [comment]
@ElizabethN -- Could you provide the document where the link is missing? Not totally sure what the Privacy: Published Guidance section is that you're referring to.

**Comment by germonprez** [comment]
Is the recommendation that we need to display this page somewhere? Maybe this could go in the KB? Under governance?

**Comment by germonprez** [comment]
As far as we can tell, this document is available through the Data Ethics disclaimer at the bottom of every metric.

**Comment by ElizabethN** [comment]
I just wanted to resurface this issue. 

@germonprez sorry, I wanted to clarify what links are missing. In [this section](https://github.com/chaoss/community/blob/main/data-use-statement.md#privacy-published-guidance) of the doc, we reference guidance in various countries but none of those link anywhere. I thought at some point we had linked out to the places we were referencing, but these are all gone.

@CBID2 I don't know if you want to work on this still, but if so, that would be amazing! Unfortunately, I can't locate the original file that held the links in [this section of the document](https://github.com/chaoss/community/blob/main/data-use-statement.md#privacy-published-guidance), so I'm guessing you'd have to google to find them again. Totally ok if you no longer have the capacity to work on this! If you do, however, I'll assign this issue to you. :blush:

**Comment by CBID2** [comment]
> I just wanted to resurface this issue. 
> 
> 
> 
> @germonprez sorry, I wanted to clarify what links are missing. In [this section](https://github.com/chaoss/community/blob/main/data-use-statement.md#privacy-published-guidance) of the doc, we reference guidance in various countries but none of those link anywhere. I thought at some point we had linked out to the places we were referencing, but these are all gone.
> 
> 
> 
> @CBID2 I don't know if you want to work on this still, but if so, that would be amazing! Unfortunately, I can't locate the original file that held the links in [this section of the document](https://github.com/chaoss/community/blob/main/data-use-statement.md#privacy-published-guidance), so I'm guessing you'd have to google to find them again. Totally ok if you no longer have the capacity to work on this! If you do, however, I'll assign this issue to you. :blush:

Sure you can @ElizabethN

**Comment by ElizabethN** [comment]
@CBID2 Thank you for handling this one! 🤩  I'll assign it to you now. No rush on it!
