### ISSUE TITLE
No access to Slack Workspace

### ISSUE THREAD

**Issue by langdon** [chaoss/community#567]
I may be doing something dumb but I can't figure out how to join the slack workspace without an invitation.

![image](https://github.com/chaoss/community/assets/1832177/b1711f61-36b5-4ed9-9be0-c352989d7515)

Am I not using the right path? I got [there](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-1fah5gu35-5oUQEPT32O2Zt~3MFVNMlw) from the [New Contributor](https://chaoss.community/kb-getting-started/) page.

**Comment by ElizabethN** [comment]
@langdon sorry for your troubles! I'll troubleshoot that link but in the meantime, try[ this one](https://join.slack.com/t/chaoss-workspace/shared_invite/zt-28p56bayt-67TRjdA4yJWQmUd4hCzULg). 🤞

**Comment by langdon** [comment]
ah ha! much better, thanks!

**Comment by ElizabethN** [comment]
Great! Glad to hear it, @langdon!

**Comment by langdon** [comment]
just fyi, this is still occurring for my students.
