### ISSUE TITLE
CHAOSScon NA 2024 Planning

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/community#594]
# CHAOSScon NA 2024
**Date:**
**Location:** Seattle, WA
**In conjunction with:** OSSNA

## Planning Committee

Project Managers: @yigakpoa and @the-techgurl

🎬 **Overall Event Coordinator:** @sgoggins 
(This role is responsible for overseeing the whole CHAOSScon Planning process)

🎪 **Venue Coordinator:** @geekygirldawn 
(This role is responsible for being the single point of contact between us and the LF event staff. If applicable, also responsible for arranging catering.)

✍️ **Content Coordinator:** @GeorgLink 
(This role is responsible for finalizing the agenda, and if applicable, managing the CfP process.)

🗣️ **Speaker Coordinator:** @vinodkahuja 
(This role is responsible for being the point of contact for speakers to make sure they have what they need.)

✨**Outreach Coordinator:** @ElizabethN 
(This role is responsible for the website, event promotion (and if applicable, ticket sales, and connecting with attendees pre-event.)

💰 **Sponsorship and Social Event Coordinator:** TBD
(This role is responsible for interacting and facilitating sponsorships and financial transactions to CHAOSS.)

🎤 **Audio Coordinator:** TBD
(This role is responsible for handling audio at the event and streaming, if applicable.)

[Planning Template Doc](https://github.com/chaoss/community/edit/main/community-operations/chaosscon.md) 

---

## Planning Checklist:

Weekly Meeting facilitation: Overall Event Coordinator

**6 months before Event:**

- [x] Secure venue (Venue Coordinator)
- [x] Confirm time block for event (Venue Coordinator)
- [x] Optional: Release and advertise CFP (Content Coordinator)
- [x] Optional: Find Sponsors (Sponsorship Coordinator)
- [x] Launch registration page (Outreach Coordinator)

**3 months before Event:**

- [x] Decide on Speakers (Content Coordinator + Planning Committee)
- [x] Decide on Keynotes (Content Coordinator + Planning Committee)
- [x] Release and advertise the schedule (Outreach Coordinator)

**2 months before Event:**

- [ ] Confirm catering (Venue Coordinator)
- [x] Determine Master of Ceremony (Content Coordinator)
- [ ] Confirm Streaming (Audio Coordinator)

**1 week before Event:**
- [ ] Upload Presentation Slides and connect with Speakers (Speaker Coordinator)
- [ ] Print name tags (Outreach Coordinator)
- [ ] If applicable, connect with Attendees (Outreach Coordinator)

**Day of Event:**
- [ ] Prepare venue signage (Venue Coordinator)
- [ ] Prepare registration table and check in attendees (Outreach Coordinator)
- [ ] Ensure Streaming is operational and Audio needs are met (Audio Coordinator)

**After Event:**
- [ ] Post-event Followup (Outreach Coordinator)

**Comment by vinodkahuja** [comment]
Since I plan on coming, you can put me as Speaker Coordinator.

**Comment by ElizabethN** [comment]
2/20 Update - We **can** have a sponsor for the social event. Ildiko will look at some potential venues.
