### ISSUE TITLE
Define 'Path to Maintainership' and 'List Maintainers'

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/community#6]
Per proposal in chaoss/governance#5 :

> The README.md of the repository contains a list of who is maintainer. Each CHAOSS repositry brings together different people and they document in the repository specific CONTRIBUTING.md how somone becomes a maintainer on their repository.

TODO:
- Specify 'path to maintainership' for this repo in CONTRIBUTING.md file
- List current maintainers in README.md file

**Comment by ElizabethN** [comment]
This has been addressed in the [Community Handbook](https://handbook.chaoss.community/community-handbook/about/path-to-leadership), so I'm closing this issue.
