### ISSUE TITLE
6 months before Event: Optional: Find Sponsors

### ISSUE THREAD

**Issue by the-techgurl** [chaoss/community#607]
-  Optional: Find Sponsors for CHAOSScon NA 2024
- To be overseen by the Sponsorship Coordinator- TBD

**Comment by geekygirldawn** [comment]
The event itself will be free, so we don't have any costs, but it would be awesome to get a sponsor for drinks / snacks somewhere after the event.

**Comment by the-techgurl** [comment]
Update - We can have a sponsor for the social event. Ildiko will look at some potential venues.
