### ISSUE TITLE
Reevaluate 'inclusion' as prefix for metrics

### ISSUE THREAD

**Issue by emmairwin** [chaoss/community#637]
Sitting in the OSS Summit, there is a CTA (on the heels of XZ to focus on 'trust' (which makes sense) but what doesn't make sense is the idea that this is an area for new ideas, rather than a time build on a lot of work that already exists (and broader community) has been doing for a decade.  I think some of the work is invisible, because it's framed under the context of diversity/incursion and thus feels more  like a nice to have, than must have for people who (frankly) don't invest in those metrics, but who care about this 'trust' attribute.

I want to propose a revisiting to metrics prefixed with inclusion to evaluate if they should just be statements about how things should be done for 'trust'.   Specifically starting with[ Inclusive Leadership](https://chaoss.community/kb/metric-inclusive-leadership/), but perhaps expanding to Inclusivity Labels. Something like 'trusted leadership' or just 'Leadership'. Something like that, but less opinionated on name, than proposing we find a way to elevate and make visible this existing work for people to build on.

  So my proposal is not to change it from being about inclusion (that matters) but shift the language to make it feel more relevant to what is in front of people - and right now thats security + risk = trust.

**Comment by germonprez** [comment]
Thanks for this Emma. We talked about it in our DEI WG meeting and we are sort of leaning towards the development of a new metric -- Accountable Leadership (?). @ElizabethN is going to start this as a new metric and we would love your input when we have a bit more to share.

**Comment by emmairwin** [comment]
sounds good, sorry I couldn't make the meeting. Will follow along, contribute as I can

**Comment by ElizabethN** [comment]
I dropped this in slack, but there is a first draft of the Accountable Leadership metric [here](https://docs.google.com/document/d/1MZ0NC-G9zWPs6-RKc_MqLiekEE5a-4e-_HkYZnx_NvU/edit) for anyone who would like to contribute!

**Comment by ElizabethN** [comment]
Just doing a little cleanup in the repo today! We could never land on a solid document for this. I'm going to bring this up in the next DEI working group meeting, but for now I'm going to close this issue.
